#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: WMF 5

install:
  - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module -Name PowerShellGet -Force
        Remove-Module -Name PowerShellGet -Force
        Install-Module -Name PSake -Repository PSGallery -Force

#---------------------------------#
#       build configuration       #
#---------------------------------#

build: off
# build is performed automatically by Psake when tests run

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
# to run your custom scripts instead of automatic tests

test_script:
  - ps: |
        Invoke-Psake -taskList test

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
